export const OPEN_NEW_STANDART_MODAL = 'MODAL/OPEN_NEW_STANDART_MODAL';
export const CLOSE_NEW_STANDART_MODAL = 'MODAL/CLOSE_NEW_STANDART_MODAL';

export const OPEN_MAIN_MENU = 'MENU/OPEN_MAIN_MENU';
export const CLOSE_MAIN_MENU = 'MENU/CLOSE_MAIN_MENU';
export const TOGGLE_MAIN_MENU = 'MENU/TOGGLE_MAIN_MENU';