export const OPEN_NEW_STANDARD_MODAL = 'MODAL/OPEN_NEW_STANDARD_MODAL';
export const CLOSE_NEW_STANDARD_MODAL = 'MODAL/CLOSE_NEW_STANDARD_MODAL';
export const OPEN_VIEW_CODE_MODAL = 'MODAL/OPEN_VIEW_CODE_MODAL';
export const CLOSE_VIEW_CODE_MODAL = 'MODAL/CLOSE_VIEW_CODE_MODAL';
export const OPEN_VIEW_MATCHES_MODAL = 'MODAL/OPEN_VIEW_MATCHES_MODAL';
export const CLOSE_VIEW_MATCHES_MODAL = 'MODAL/CLOSE_VIEW_MATCHES_MODAL';
export const OPEN_DECLINE_REQUEST_MODAL = 'MODAL/OPEN_DECLINE_REQUEST_MODAL';
export const CLOSE_DECLINE_REQUEST_MODAL = 'MODAL/CLOSE_DECLINE_REQUEST_MODAL';
export const OPEN_REQUEST_DETAILS_MODAL = 'MODAL/OPEN_REQUEST_DETAILS_MODAL';
export const CLOSE_REQUEST_DETAILS_MODAL = 'MODAL/CLOSE_REQUEST_DETAILS_MODAL';

export const OPEN_MAIN_MENU = 'MENU/OPEN_MAIN_MENU';
export const CLOSE_MAIN_MENU = 'MENU/CLOSE_MAIN_MENU';
export const TOGGLE_MAIN_MENU = 'MENU/TOGGLE_MAIN_MENU';

export const ADD_NEW_TERMINOLOGY_FORM_DATA = 'TERMINOLOGY/ADD_NEW_TERMINOLOGY_FORM_DATA';
export const REMOVE_NEW_TERMINOLOGY_FORM_DATA = 'TERMINOLOGY/REMOVE_NEW_TERMINOLOGY_FORM_DATA';
export const ADD_NEW_TERMINOLOGY_ADMIN = 'TERMINOLOGY/ADD_NEW_TERMINOLOGY_ADMIN';
export const ADD_NEW_TERMINOLOGY_USER = 'TERMINOLOGY/ADD_NEW_TERMINOLOGY_USER';
export const SEND_CODE_FOR_APPROVAL = 'TERMINOLOGY/SEND_CODE_FOR_APPROVAL';
export const APPROVE_CODE = 'TERMINOLOGY/APPROVE_CODE';
export const DECLINE_CODE = 'TERMINOLOGY/DECLINE_CODE';

export const USER_LOGIN = 'USER/USER_LOGIN';
export const USER_LOGOUT = 'USER/USER_LOGOUT';

export const ADD_NOTIFICATION = 'NOTIFICATIONS/ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'NOTIFICATIONS/REMOVE_NOTIFICATION';

export const ADD_REQUEST = 'PENDING_REQUEST/ADD_REQUEST';
export const REMOVE_REQUEST = 'PENDING_REQUEST/REMOVE_REQUEST';
export const UPDATE_REQUEST = 'PENDING_REQUEST/UPDATE_REQUEST';